# Generated by Django 5.2.14 on 2026-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
