# Generated by Django 5.2.14 on 2026-06-02 12:54
from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_data(apps, schema_editor):
    User = apps.get_model('api', 'User')
    Class = apps.get_model('api', 'Class')
    UserClass = apps.get_model('api', 'UserClass')

    password = make_password("123456")

    professores = []

    for i in range(1, 6):
        professor, _ = User.objects.get_or_create(
            email=f'prof{i}@geia.pt',
            defaults={
                'name': f'Professor {i}',
                'password': password,
                'role': 'professor',
                'is_active': True,
            }
        )

        professores.append(professor)

    turmas = []

    nomes_turmas = [
        "Programação Web",
        "Bases de Dados",
        "Inteligência Artificial",
        "Engenharia de Software",
        "Sistemas Distribuídos",
    ]

    for i in range(5):
        turma, _ = Class.objects.get_or_create(
            name=nomes_turmas[i],
            course='LEI',
            year=2025,
            teacher=professores[i]
        )

        turmas.append(turma)

    aluno_num = 1

    for turma in turmas:

        for _ in range(10):

            aluno, _ = User.objects.get_or_create(
                email=f'aluno{aluno_num}@geia.pt',
                defaults={
                    'name': f'Aluno {aluno_num}',
                    'password': password,
                    'role': 'aluno',
                    'is_active': True,
                }
            )

            UserClass.objects.get_or_create(
                user=aluno,
                classroom=turma
            )

            aluno_num += 1

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260601_1217'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]

    