# Generated by Django 5.2.14 on 2026-06-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alarmingmessage'),
        ('api', '0005_auto_20260602_1254'),
    ]

    operations = [
    ]
