# Generated by Django 5.2.14 on 2026-07-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0005_alarmingmessage_0005_auto_20260602_1254'),
        ('api', '0007_userconversation_shared_by'),
    ]

    operations = [
    ]
