# Generated by Django 5.2.14 on 2026-07-01 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20260701_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClassSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.IntegerField()),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('total_messages', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_class_summary',
            },
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('messages_processed', models.IntegerField(default=0)),
                ('conversations_processed', models.IntegerField(default=0)),
                ('classes_processed', models.IntegerField(default=0)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_version', models.CharField(default='v1', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processing_batch',
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(through='api.UserConversation', through_fields=('conversation', 'user'), to='api.user'),
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('frequency', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_questions', to='api.dailyclasssummary')),
            ],
            options={
                'db_table': 'frequent_question',
            },
        ),
        migrations.AddField(
            model_name='dailyclasssummary',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='api.processingbatch'),
        ),
        migrations.CreateModel(
            name='TopicInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('mentions_count', models.IntegerField(default=0)),
                ('students_affected_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('teacher_recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_insights', to='api.dailyclasssummary')),
            ],
            options={
                'db_table': 'topic_insight',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyclasssummary',
            unique_together={('classroom_id', 'date')},
        ),
    ]
