# Generated by Django 5.2.15 on 2026-07-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dailyclasssummary_processingbatch_and_more'),
        ('api', '0011_studentdoubtmessage'),
    ]

    operations = [
    ]
