# Generated by Django 5.2.15 on 2026-07-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_merge_20260708_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.class'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(through='api.UserConversation', through_fields=('conversation', 'user'), to='api.user'),
        ),
        migrations.CreateModel(
            name='ClassSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('conversation_count', models.PositiveIntegerField(default=0)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('llm_model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ("classroom_id",models.PositiveIntegerField()),
            ],
        ),
    ]
