# Generated by Django 5.2.15 on 2026-07-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_conversation_classroom_alter_conversation_users_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyclasssummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyclasssummary',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='frequentquestion',
            name='daily_summary',
        ),
        migrations.RemoveField(
            model_name='topicinsight',
            name='daily_summary',
        ),
        migrations.DeleteModel(
            name='ProcessingBatch',
        ),
        migrations.DeleteModel(
            name='FrequentQuestion',
        ),
        migrations.DeleteModel(
            name='DailyClassSummary',
        ),
        migrations.DeleteModel(
            name='TopicInsight',
        ),
    ]
