# Generated by Django 5.2.15 on 2026-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dailyclasssummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor')], default='student', max_length=20),
        ),
    ]
